name: conveniently
description: Conveniently helps you write Dart code conveniently. It provides various extension functions for very common operations.
version: 1.3.0
repository: https://github.com/renatoathaydes/conveniently

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
